### ISSUE TITLE
THere should be at least 4 more raycoons on the page

### ISSUE THREAD

**Issue by jeffrand** [tessjoh/tessjoh.github.io#2]
Please fix soon

**Comment by enkeboll** [comment]
+1 i also have this porblem

**Comment by tessjoh** [comment]
porblem can be replicated on moble

**Comment by tessjoh** [comment]
dont have time to fix though, have to pick up adult sons from daycare

**Comment by tm310** [comment]
This is bug.

**Comment by tessjoh** [comment]
thank you thorton

**Comment by enkeboll** [comment]
bugs don't work for me on Windows Mobile please transformulate into raycoons please

**Comment by jeffrand** [comment]
@tessjoh bump please this is ruining mt use of this website

**Comment by tessjoh** [comment]
@jeffrand additional raccoon's have been added

**Comment by enkeboll** [comment]
unsubscribe

**Comment by jeffrand** [comment]
Sick
